import { SideBar } from '@/components/ui/Sidebar-'
import { Toaster } from '@/components/ui/toaster'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-calc(100dvw-80px) flex h-dvh flex-col lg:flex-row">
          <SideBar />
          {children}
        </div>
      </body>
      <Toaster />
    </html>
  )
}
