import { Toaster } from '@/components/ui/toaster'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { PrimeReactProvider } from 'primereact/api'
import './globals.css'

import { Sidebar } from '@/components/sidebar'
import 'primereact/resources/themes/lara-light-cyan/theme.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full flex h-dvh  ">
          <PrimeReactProvider value={{ unstyled: true }}>
            <Sidebar />
            {children}
          </PrimeReactProvider>
        </div>
      </body>
      <Toaster />
    </html>
  )
}
